<? 
$productID = "SciELO setup";
$messageArray = array (
	"es" =>
		array (
			"title" => "$productID: proceso de configuración",
			"msg1" => "Ajustando archivos del sistema ...",
			"msg2" => "Directório: ",
			"msg3" => "Archivos: ",
			"end"	=> "::Configuración finalizada.",
			"error" => "::Error en el proceso de configuración. Por favor verifique los permisos del directorio y archivos del sistema y ejecute el setup nuevamente.",
			"error-wxis" => "::Error en el proceso generación de las bases del sistema. Verifique los permisos del directorio y archivos, permiso de ejecucion en el directório /cgi-bin/ y licencia de uso del software wxis",
			"back" => "Volver",
			"master_exist" => "base de datos ya fue creada",
			"home" => "Página inicial"
		),
	"pt" =>
		array (
			"title" => "$productID: processo de configuração",
			"msg1" => "Ajustando arquivos do sistema ...",
			"msg2" => "Diretório: ",
			"msg3" => "Arquivos: ",
			"end"	=> "::Configuração finalizada.",
			"error" => "::Erro no processo de configuração. Por favor verifique a permissão do diretório e arquivos do sistema e execute o setup novamente.",
			"error-wxis" => "::Erro no processo de geração das bases do sistema. Verifique as permissões do diretório e arquivos, permissão de execução no diretório /cgi-bin/ e licença de uso do software wxis",
			"back" => "Retornar",
			"master_exist" => "base de dados já foi criada",
			"home" => "Página inicial"
		),
	"en" =>
		array (
			"title" => "$productID: setup process",
			"msg1" => "Adjusting system files ...",
			"msg2" => "Path: ",
			"msg3" => "Files: :",
			"end"	=> "::Setup complete.",
			"error" => "::Error in setup process. Please check permission of system files and directory and execute setup.",
			"error-wxis" => "::Error in database setup process. Please check permission of system files and directory, permission of /cgi-bin/ directory and wxis licence file",
			"back" => "Back",
			"master_exist" => "database already created",
			"home" => "Home",
		),
);

?>
