<? 
$productID = "SciELO setup";
$messageArray = array (
	"es" =>
		array (
			"title" => "$productID: configuración",
			"para1" => "<p>El Setup encontró la información necesaria para instalar <b>$productID</b>.<br>Lea atentamente la siguiente información y altérela si es necesario.</p>",
			"server" => "Nombre del servidor: ",
			"server_path" => "Directorio raíz: ",
            "para2" => "<br><p>Caminos para los directorios donde los archivos del <b>$productID</b> fueron instalados.</p>",
			"htdocs" => ". documentos: ",
			"cgi_path" => ". cgi-bin: ",
			"db_path" => ". bases: ",
			"para3" => "<p>Al presionar el botón \"Próximo\" el Setup empezará a procesar los archivos de la aplicación basandose en la información descrita.</p>",
			"apply" => "Próximo",
			"obs1" => "no es necesario alterar",
			"obs2" => "confirma/altera",
			"language" => "<a href='?lang=pt'>português</a>  |  <a href='?lang=en'>english</a>"
		),
	"pt" =>
		array (
			"title" => "$productID: configuração",
			"para1" => "<p>O Setup encontrou a informação necessária para instalar <b>$productID</b>.<br>Leia atentamente a informação abaixo e altere-a se necessário.</p>",
			"server" => "Nome do servidor: ",
			"server_path" => "Diretório raíz: ",
            "para2" => "<br><p>Caminhos para os diretórios onde os arquivos de <b>$productID</b> foram instalados.</p>",
			"htdocs" => ". documentos: ",
			"cgi_path" => ". cgi-bin: ",
			"db_path" => ". bases: ",
			"para3" => "<p>Ao pressionar o botão \"Próximo\" o Setup começará a processar os arquivos da aplicação baseando-se na informação acima.</p>",
			"apply" => "Próximo",
			"obs1" => "não é necessário alterar",
			"obs2" => "confirma/altera",
			"language" => "<a href='?lang=es'>español</a>  |  <a href='?lang=en'>english</a>"
		),
	"en" =>
		array (
			"title" => "$productID: setup",
			"para1" => "<p>The setup has found the information required to install <b>$productID</b>.<br>Read carefully the information below and change it whenever necessary.</p>",
			"server" => "Servername: ",
			"server_path" => "Root directory: ",
            "para2" => "<br><p>Paths to directories where <b>$productID</b> files have been installed.</p>",
			"htdocs" => ". documents: ",
			"cgi_path" => ". cgi-bin: ",
			"db_path" => ". bases: ",
			"para3" => "<p>By pressing the \"Next\" button Setup will start processing application files based on the information given above.</p>",
			"apply" => "Next",
			"obs1" => "do not need changing",
			"obs2" => "confirm/change",
			"language" => "<a href='?lang=pt'>português</a>  |  <a href='?lang=es'>español</a>"
		),
);
?>
