services:
  scielo-web:
    platform: linux/amd64
    image: infrascielo/metodologia:v7.1-qa
    container_name: scielo-web-rocky9
    ports:
      - "80:80"
    environment:
      SERVER_SCIELO: ${SERVER_SCIELO:-cienciaecultura.bvs.br}
    volumes:
      - /Users/rondinelisaad/Downloads/repo-scielo/comciencia_scielo_br_new:/var/www/html
    restart: unless-stopped
