COLLECTION = 'SciELO Brasil'
CISIS_DIR = '/usr/local/bireme/cisis/5.5.pre02/linux/lindG4/'
XML_SERIAL_LOCATION = '../bases_xml.000/serial'
MAIL_TO = 'marcacao@scielo.org'
MAIL_CC = 'infra@scielo.org, producao@scielo.org'
MAIL_BCC = 'roberta.takenaka@scielo.org'
PROC_SERIAL_LOCATION = '../serial'
