VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ClIssue"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public database As String
Public update As String
Public recordtp As String
Public recordid As String
Public rectpid As String
Public doccount As String
Public cover As String
Public stitle As String
Public sertitle As String
Public alttitle As String
Public isstitle As String
Public edname As String
Public dateiso As String
Public year As String
Public month As String
Public status As String
Public issueno As String
Public issuept As String
Public supplvol As String
Public supplno As String
Public iseqno As String
Public issn As String
Public volid As String
Public pubid As String
Public siglum As String

