BATCHES_PATH=langs/linux/
PROCLANG_PATH=langs/

MX=cisis/mx
BASESWORK=../bases-work
PATH_DBLANG=../bases-work/lang
DBLANG=../bases-work/lang/lang
DBLANGTAB=../bases-work/lang/langtab

PROCLANG_LOG=log/langs.log
PROCLANG_REPORT_LOG=log/langs_report.log
FILE_CIPAR=$PROCLANG_PATH/config/cipar.cip
FILE_CONFIG=$PROCLANG_PATH/config/config.inc

TITLE=../bases/title/title
NEW_SCILISTA=temp/langs_new_scilista.txt
TEMP_DBLANG=temp/langs_dblang

PATH_FILES=/home/scielo/www/langs

xmount=true
PATH_PROC=

GZM_ISSN=temp/langs_gzm_issn
GZM_DOCTOPIC=temp/langs_gzm_doctopic
GZM_OT=temp/langs_gzm_ot
GZM_LANG=temp/langs_gzm_lang
GZM_TAB=temp/langs_gzm_tab

REPORTS_PATH=../bases-work/lang/report