<?
require_once(dirname(__FILE__)."/functions.php");

$campos = array('address' => 'address',
						 'annote' => 'annote',
						 'author' => 'author',
						 'booktitle' => 'booktitle',
						 'chapter' => 'chapter',
						 'crossref' => 'crossref',
						 'edition' => 'edition',
						 'editor' => 'editor',
						 'howpublished' => 'howpublished',
						 'institution' => 'institution',
						 'journal' => 'journal',
						 'key' => 'key',
						 'month' => 'month',
						 'note' => 'note',
						 'number' => 'number',
						 'organization' => 'organization',
						 'pages' => 'pages',
						 'publisher' => 'publisher',
						 'school' => 'school',
						 'series' => 'series',
						 'title' => 'title',
						 'type' => 'type',
						 'volume' => 'volume',
						 'year' => 'year',
						 'affiliation' => 'affiliation',
						 'abstract' => 'abstract',
						 'contents' => 'contents',
						 'copyright' => 'copyright',
						 'ISBN' => 'ISBN',
						 'ISSN' => 'ISSN',
						 'keywords' => 'keywords',
						 'language' => 'language',
						 'location' => 'location',
						 'LCCN' => 'LCCN',
						 'mrnumber' => 'mrnumber',
						 'price' => 'price',
						 'size' => 'size',
						 'URL' => 'URL');

echo export2BibTeX("article",$campos);
?>