<?
/*
Faz o logout na instancia (ou seja "mata" os cookies de usuario) 
*/
    session_start();
    setcookie("userID","",0,"/");
    setcookie("userFirstName","",0,"/");
    setcookie("userLastName","",0,"/");
    setcookie("userToken","",0,"/");
    unset($_COOKIE['userID']);
    unset($_COOKIE['userFirstName']);
    unset($_COOKIE['userLastName']);
    unset($_COOKIE['userToken']);
    unset($_SESSION['checkedLogin']);
?>
<html>
<body>
<p>Logout</p>
</body>
</html>
