BATCHES_PATH=langs/linux/
PROCLANG_PATH=langs/

MX=cisis/mx
BASESWORK=../bases-work
DBLANG=../bases-work/lang/lang
PROCLANG_LOG=log/langs.log
FILE_CIPAR=$PROCLANG_PATH/config/cipar.cip
FILE_CONFIG=$PROCLANG_PATH/config/config.inc

TITLE=../bases-work/title/title
NEW_SCILISTA=temp/langs_new_scilista.txt
TEMP_DBLANG=temp/langs_dblang

PATH_FILES=/home/scielo/www/langs

xmount=true
PATH_PROC=
