	,'d*',
	,'a880{',v1,'{',
	if p(v2) then ,'a1{',v2,'{', fi,
	,'a2{',v3,'^d',date,'{',
	,'a3{',if size(v1)>23 then 'ref' else 'art' fi,'{',
	,'a91{',date,'{',
	,if p(v2) and v2<>'' then
		,'a999{^uhttp://dx.doi.org/',v2,'^lCrossRef{',
	,fi,
	,'a900{',v900,'{',
