ServerName localhost

DocumentRoot "/var/www/html/htdocs"
DirectoryIndex scielo.php index.php index.html

Alias /pdf/ "/var/www/html/bases/pdf/"

<Directory "/var/www/html/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<Directory "/var/www/html/bases/pdf/">
    Options FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

<Directory "/var/www/html/cgi-bin">
    Options +ExecCGI +FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
