
TEMPLATE=200910
PATH_TEMPLATE=journalEvaluation/current/template/$TEMPLATE
MX=lindG4/mx
CPFILE=journalEvaluation/current/config/avaliacao.cip
OUTPUT_PATH=/home/scielo/www/htdocs/teste/journalEvaluation/current/data/$TEMPLATE
REL_OUTPUT_PATH=/teste/journalEvaluation/current/data/$TEMPLATE
SCILISTA=temp/avaliacao_permanencia_scilista.lst
ISSUEQTD=3
HTML_FILE_OUTPUT=$OUTPUT_PATH/journals.htm
JOURNAL_EDBOARD_HTML_PATH=/home/scielo/www/htdocs/revistas/
AFFLISTCOMPLETA=journalEvaluation/common/gizmo/affcompleta
PATH_GZM=journalEvaluation/common/gizmo
PATH_SHELL=journalEvaluation/current/linux
PATH_COMMON=journalEvaluation/common
AFFSEQ=temp/v70.seq
AVALLOG=log/avaliacao_permanencia.log
PARAM_SELECT_BY_YEAR=2008
PARAM_SELECT_BY_RECENT=

FILE_SELECTED_ISSUES=temp/journalEvaluation_selected_issues.txt
SEQFILEALLISSUESELECTED=temp/allissuesselected.txt

JournalFileName=journaldata.txt